# Generated by Django 2.1 on 2018-08-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_property_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/default_user.png', upload_to='static/uploads'),
        ),
    ]
