# Generated by Django 2.1 on 2018-09-13 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180830_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='propertyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='app.Property'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='tenantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
