# Generated by Django 2.1 on 2018-09-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180920_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='uncrate.com/p/2016/09/simmerberg-house-1.jpg', upload_to='static/uploads'),
        ),
    ]
