# Generated by Django 2.1 on 2018-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='https://uncrate.com/p/2016/09/simmerberg-house-1.jpg', upload_to='static/uploads'),
        ),
    ]
