# Generated by Django 2.1 on 2018-10-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180930_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_time',
            new_name='occupied_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
    ]
