# Generated by Django 2.1 on 2018-10-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181002_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tenant_number',
            field=models.IntegerField(default=1),
        ),
    ]
