# Generated by Django 2.1 on 2018-10-16 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181016_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
