# Generated by Django 2.1 on 2018-10-16 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_comment_star_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='star_rate',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
