# Generated by Django 2.1 on 2018-10-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181016_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(default=''),
        ),
    ]
