# Generated by Django 2.1 on 2018-10-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(default='Elevator#Pets allowed#Internet#Indoor fireplace#Breakfast#Buzzer/wireless intercom#Heating#Gym#Wheelchair accessible#Family/kid friendly#Doorman#Wireless Internet#Kitchen#Free parking on premises#Hot tub#Cable TV#Suitable for events#Iron#Smoking allowed#Hair dryer#Dryer#Washer#Shampoo#Laptop friendly workspace#Pool#TV#Air conditioning#Hangers#Essentials#Private entrance#Free parking on street#Paid parking off premises#'),
        ),
    ]
